### ISSUE TITLE
Booleans

### ISSUE THREAD

**Issue by njordhov** [zexxlin/clarity-blind-poll#1]
You don't have to define constants for `true` and `false` as they're already [predefined](https://docs.blockstack.org/core/smart/clarityref#true).

https://github.com/zexxlin/clarity-blind-poll/blob/7f5bada918ecb4854f7b831b84ddc09370b072c8/contracts/blind-poll.clar#L8-L9

**Comment by zexxlin** [comment]
Thank you. It seems I was using an older version of **clarity-lsp** plugin in VS Code, which does not recognize boolean keywords.
